# Generated by Django 3.1.5 on 2021-01-23 06:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_auto_20210122_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(default='images/defaults/videos.jpg', upload_to='videos/%y/thumbnails/'),
        ),
        migrations.CreateModel(
            name='AudioPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/%y/')),
                ('caption', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(default='images/defaults/headphone_audio.jpg', upload_to='audio/%y/thumbnails/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='base.Category')),
            ],
        ),
    ]
