# Generated by Django 3.1.5 on 2021-01-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210123_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaults/kobydrillsdotkom.png', upload_to='images'),
        ),
    ]
